#ifndef STOPWATCH_FIXED_GLOBAL_H
#define STOPWATCH_FIXED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STOPWATCH_FIXED_LIBRARY)
#  define STOPWATCH_FIXED_EXPORT Q_DECL_EXPORT
#else
#  define STOPWATCH_FIXED_EXPORT Q_DECL_IMPORT
#endif

#endif // STOPWATCH_FIXED_GLOBAL_H
